# Generated by Django 2.0.1 on 2018-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_file', models.FileField(upload_to='')),
                ('courses_file', models.FileField(upload_to='')),
            ],
        ),
    ]
