# Generated by Django 2.0.1 on 2018-01-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='database',
        ),
        migrations.AlterField(
            model_name='question',
            name='parentsQuestionPosition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
    ]
