# Generated by Django 2.0.1 on 2018-01-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180120_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='position',
        ),
        migrations.AddField(
            model_name='question',
            name='previousQuestion',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prev_question', to='api.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='parentsQuestionPosition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentsQuestion', to='api.Question'),
        ),
    ]
