# Generated by Django 2.0.1 on 2018-01-20 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180120_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Veuillez choisir un type de question parmi select, selectOne, inline ou text', regex='^(select|selectOne|inline|text)$')]),
        ),
    ]
