# Generated by Django 2.0.1 on 2018-01-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180120_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='previousQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='parentsQuestionPosition',
            field=models.IntegerField(default=0),
        ),
    ]
