# Generated by Django 2.0 on 2018-01-02 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, default='')),
                ('submissionDate', models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 2, 20, 49, 35, 593773, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('commissionsDate', models.DateTimeField()),
                ('availableDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('resume', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=300)),
                ('obligatory', models.BooleanField(default=False)),
                ('type_question', models.CharField(max_length=50)),
                ('type_data', models.CharField(max_length=400)),
                ('isSub', models.BooleanField(max_length=50)),
                ('parentsQuestionPosition', models.IntegerField(default=False)),
                ('parentsquestionsValue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypeForm'),
        ),
        migrations.AddField(
            model_name='group',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='typeForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypeForm'),
        ),
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
