# Generated by Django 2.0 on 2018-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeform',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
