# Generated by Django 2.0 on 2018-01-02 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submissionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 2, 20, 52, 13, 585923, tzinfo=utc)),
        ),
    ]
