# Generated by Django 2.0 on 2017-12-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171229_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
