# Generated by Django 2.0 on 2018-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_typeform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_data',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='typeform',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
