# Generated by Django 2.0 on 2018-01-02 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180102_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submissionDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
