# Generated by Django 2.0 on 2018-01-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180102_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='ldap',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
